openapi: 3.0.0
info:
  title: Todo Application API
  description: API for multi-user Todo web application with authentication
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server

paths:
  /api/{user_id}/tasks:
    get:
      summary: Get all tasks for a user
      description: Retrieve all tasks belonging to the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user whose tasks to retrieve
          schema:
            type: string
      responses:
        '200':
          description: List of tasks for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User does not have access to this user's tasks
        '404':
          description: User not found
      security:
        - jwt_auth: []
    post:
      summary: Create a new task
      description: Create a new task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user to create the task for
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User does not have access to this user's tasks
        '422':
          description: Validation error
      security:
        - jwt_auth: []

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task by ID for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User does not have access to this task
        '404':
          description: Task not found
      security:
        - jwt_auth: []
    put:
      summary: Update a task
      description: Update all fields of a specific task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User does not have access to this task
        '404':
          description: Task not found
        '422':
          description: Validation error
      security:
        - jwt_auth: []
    delete:
      summary: Delete a task
      description: Delete a specific task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to delete
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User does not have access to this task
        '404':
          description: Task not found
      security:
        - jwt_auth: []

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Mark task as complete/incomplete
      description: Toggle the completion status of a specific task
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_completed:
                  type: boolean
                  description: Whether the task is completed
              required:
                - is_completed
      responses:
        '200':
          description: Task completion status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT token
        '403':
          description: Forbidden - User does not have access to this task
        '404':
          description: Task not found
        '422':
          description: Validation error
      security:
        - jwt_auth: []

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the task
        user_id:
          type: string
          description: ID of the user who owns this task
        title:
          type: string
          description: Title of the task
          maxLength: 200
        description:
          type: string
          description: Detailed description of the task
        is_completed:
          type: boolean
          description: Whether the task is marked as complete
          default: false
        due_date:
          type: string
          format: date-time
          description: Optional deadline for the task
        priority:
          type: string
          enum: [low, medium, high]
          description: Priority level of the task
          default: medium
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last updated
        completed_at:
          type: string
          format: date-time
          description: Timestamp when task was marked as complete (null if not completed)
      required:
        - id
        - user_id
        - title
        - is_completed
        - created_at
        - updated_at

    TaskCreate:
      type: object
      properties:
        title:
          type: string
          description: Title of the task
          maxLength: 200
        description:
          type: string
          description: Detailed description of the task
        due_date:
          type: string
          format: date-time
          description: Optional deadline for the task
        priority:
          type: string
          enum: [low, medium, high]
          description: Priority level of the task
          default: medium
      required:
        - title

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Title of the task
          maxLength: 200
        description:
          type: string
          description: Detailed description of the task
        due_date:
          type: string
          format: date-time
          description: Optional deadline for the task
        priority:
          type: string
          enum: [low, medium, high]
          description: Priority level of the task
        is_completed:
          type: boolean
          description: Whether the task is marked as complete
      required:
        - title

  securitySchemes:
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token required for authentication